package com.ldm.marioconga.juego;

import com.ldm.marioconga.Musica;
import com.ldm.marioconga.Pixmap;
import com.ldm.marioconga.Sonido;

public class Assets {
    public static Pixmap fondo;
    public static Pixmap logo;
    public static Pixmap menuprincipal;
    public static Pixmap pantalla_personajes;
    public static Pixmap botones;
    public static Pixmap ayuda1;
    public static Pixmap ayuda2;
    public static Pixmap ayuda3;
    public static Pixmap numeros;
    public static Pixmap preparado;
    public static Pixmap menupausa;
    public static Pixmap finjuego;
    public static Pixmap mario_arriba;
    public static Pixmap mario_izquierda;
    public static Pixmap mario_abajo;
    public static Pixmap mario_derecha;
    public static Pixmap luigi_arriba;
    public static Pixmap luigi_izquierda;
    public static Pixmap luigi_abajo;
    public static Pixmap luigi_derecha;
    public static Pixmap peach_arriba;
    public static Pixmap peach_izquierda;
    public static Pixmap peach_abajo;
    public static Pixmap peach_derecha;
    public static Pixmap estela_arriba;
    public static Pixmap estela_izquierda;
    public static Pixmap estela_abajo;
    public static Pixmap estela_derecha;
    public static Pixmap bowser_arriba;
    public static Pixmap bowser_izquierda;
    public static Pixmap bowser_abajo;
    public static Pixmap bowser_derecha;
    public static Pixmap yoshi_arriba;
    public static Pixmap yoshi_izquierda;
    public static Pixmap yoshi_abajo;
    public static Pixmap yoshi_derecha;
    public static Pixmap mario_bebe;
    public static Pixmap luigi_bebe;
    public static Pixmap peach_bebe;
    public static Pixmap destello;
    public static Pixmap bowser_jr;
    public static Pixmap melocoton;
    public static Pixmap melocoton_azul;
    public static Pixmap melocoton_dorado;
    public static Pixmap planta;
    public static Pixmap caparazon;
    public static Pixmap corazon;
    public static Pixmap corazon_azul;
    public static Pixmap corazon_dorado;
    public static Pixmap huevo_amarillo;
    public static Pixmap huevo_azul;
    public static Pixmap huevo_rosa;
    public static Pixmap rey_goomba;
    public static Pixmap lady_bow;
    public static Pixmap bala;
    public static Pixmap huevos;
    public static Pixmap premio1;
    public static Pixmap premio2;
    public static Pixmap premio3;
    public static Pixmap goomba;
    public static Pixmap boo;
    public static Pixmap bootler;
    public static Pixmap dark_boo_rey;
    public static Pixmap dark_boo;
    public static Pixmap boo_rey1;
    public static Pixmap boo_rey2;

    public static Sonido start;
    public static Sonido pulsar;
    public static Sonido sonido_seta;
    public static Sonido derrota;
    public static Sonido pausa;
    public static Sonido mario;
    public static Sonido luigi;
    public static Sonido peach;
    public static Sonido estela;
    public static Sonido bowser;
    public static Sonido yoshi;
    public static Musica partida;

}